### ISSUE TITLE
Correção de bug na descrição do projeto

### ISSUE THREAD

**Issue by djedu28** [lucenfort/python-snippets#1]
❌Está escrito " oletânea de programas simples em Python "
![image](https://user-images.githubusercontent.com/43933482/230762881-67acbab4-72cb-4605-bd4a-5612d00a08b2.png)

⚠Faltou o "C" no início da frase.

🟢
``` 
 🐍Coletânea de programas simples em Python 
```

**Comment by lucenfort** [comment]
Corrigido o bug na descrição do projeto, agradeço o aviso @djedu28
